# Generated by Django 2.2 on 2019-06-22 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.CharField(max_length=250)),
                ('Account', models.TextField()),
                ('status', models.CharField(choices=[('clear', 'Clear'), ('checked', 'Checked'), ('waiting', 'Waiting'), ('awaited', 'Awaited'), ('unknown', 'Unknown'), ('returned', 'Returned')], default='Unknown', max_length=10)),
                ('URL', models.SlugField(max_length=250, unique_for_date='Desigated')),
                ('Designated', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Database', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
