# Generated by Django 2.2 on 2019-06-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='status',
            new_name='Status',
        ),
    ]
