# Generated by Django 2.2 on 2019-06-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20190622_0911'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collection',
            table='AMURoboclub_Database',
        ),
    ]
