# Generated by Django 2.2 on 2019-06-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20190622_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('Designated',)},
        ),
    ]
