# Generated by Django 2.2 on 2019-06-22 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Database', '0004_auto_20190622_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collection',
            new_name='AMURoboclub',
        ),
    ]
